project: 
  type: website
  output-dir: "." 

website:
  title: "Hayden Mikula"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: R-Basics
        href: danl-310-quarto-r.qmd
      - text: Python Data Analysis
        menu:
          - text: Pandas Basics
            href: pandas_basics.ipynb
          - text: Seaborn Basics
            href: seaborn_basics.ipynb
      - text: DANL 210 Final Project
        href: danl_210_hayden_mikula_stock_esg.ipynb
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Hayden Mikula, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

